name: Build and Deploy

on:
  push:
    branches: [ main ]  # 假设您的主分支是main，如果是master请修改此处
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # 设置Node.js环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # 使用Node.js 18版本
    
    # 安装pnpm
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8  # 使用pnpm 8版本，可根据需要调整
        run_install: false
    
    # 获取pnpm存储目录路径以进行缓存
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    
    # 设置缓存，提高CI构建速度
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    
    # 安装依赖
    - name: Install dependencies
      run: pnpm install
    
    # 构建项目
    - name: Build
      run: pnpm build
    
    # 部署到GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist  # Vite默认构建输出目录
        branch: gh-pages  # 部署到的分支
